version: '3'

services:
  fleetman-queue:
    image: mlflacr23.azurecr.io/k8s-fleetman-queue:release2
    ports:
      - '8161:8161'
    environment:
      - SPRING_PROFILES_ACTIVE=production-microservice

  fleetman-webapp:
    image: mlflacr23.azurecr.io/k8s-fleetman-webapp-angular:release2
    ports:
      - '80:80'
    environment:
      - SPRING_PROFILES_ACTIVE=production-microservice

  fleetman-api-gateway:
    image: mlflacr23.azurecr.io/k8s-fleetman-api-gateway:release2
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=production-microservice

  fleetman-position-simulator:
    image: mlflacr23.azurecr.io/k8s-fleetman-position-simulator:release2
    environment:
      - SPRING_PROFILES_ACTIVE=production-microservice

  fleetman-position-tracker:
    image: mlflacr23.azurecr.io/k8s-fleetman-position-tracker:release3
    environment:
      - SPRING_PROFILES_ACTIVE=production-microservice

  fleetman-mongodb:
    image: mongo:3.6.5-jessie
    ports:
      - '27017:27017'
